name: EKS Setup Pipeline

on:
  push:
    branches:
      - main  
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 3: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7  # Specify the Terraform version you use
        
    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: |
        cd terraform-eks-code
        terraform init

    # Step 5: Run Terraform Plan
    - name: Terraform Plan
      run: |
        cd terraform-eks-code
        terraform plan

    # Step 6: Apply Terraform Plan (creates resources like VPC, EKS, and ECR)
    - name: Terraform Apply
      run: |
        cd terraform-eks-code
        terraform apply -auto-approve

    # Step 7: Set up kubectl (to interact with the EKS cluster after setup)
    - name: Set up kubectl
      run: |
        aws eks --region us-east-1 update-kubeconfig --name sreekanth-eks-cluster
        kubectl get nodes
